# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/clean-mountain-395906/your-django-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/clean-mountain-395906/your-django-app']
  - name: 'sonarsource/sonar-scanner-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sonar-scanner
        -Dsonar.projectKey=cleanmoutain_cleane \
        -Dsonar.organization=cleanmoutain \
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.login=$_SONAR_TOKEN
